import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { DateRangeProvider } from '@/context/DateRangeContext'; 

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <DateRangeProvider> {/* Wrap the app with DateRangeProvider */}
          {children}
          <Toaster />
        </DateRangeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}